services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    env_file:
      - .env
    command: tunnel run
    environment:
      TZ: ${TZ}
      TUNNEL_TOKEN: ${TUNNEL_TOKEN}
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    networks:
      - dev-network
networks:
  dev-network:
    external: true
